apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: art-gallery

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- configmap.yaml

images:
- name: art-gallery
  newTag: latest

commonLabels:
  app: art-gallery
  version: v1.0.0